// src/import/domain/importReasons.js

export const IMPORT_REASONS = {
	SPOT_READY: "SPOT_READY",
	CRS_NEEDED: "CRS_NEEDED",
	TRANSITION_MAPPING_NEEDED: "TRANSITION_MAPPING_NEEDED",
	SPARSE_BUILD_FAILED: "SPARSE_BUILD_FAILED",
	UNSUPPORTED_GEOMETRY: "UNSUPPORTED_GEOMETRY",
};
