import { buildEngineeringCommandPaletteModel } from "../../domain/workspace/buildEngineeringCommandPaletteModel.js";
const PEER_OPENERS = new Set(["btnGndImportWorkbench", "btnSpot", "btnAlignmentEditor", "btnVerticalProfileAuthoring", "btnCantAuthoring", "btnChainageAuthoring"]);

export function createEngineeringCommandPaletteController({ documentRef = globalThis.document, windowRef = globalThis.window, view, getContext, availability, watchToolSurface = () => () => {}, clearToolSurface = () => {} } = {}) {
	let open = false, busy = false, query = "", selectedId = null, stopResponsive = null, trigger = null, error = null;
	const overlay = documentRef.getElementById("engineeringCommandPaletteOverlay"), button = documentRef.getElementById("btnCommandPalette");
	function model() { return buildEngineeringCommandPaletteModel({ activeObjectId: getContext?.()?.objectId, availability, query, selectedId, busy, error }); }
	function render() { const value = model(); selectedId = value.selectedId; view.render(value); return value; }
	function close() { if (!open) return; open = false; stopResponsive?.(); stopResponsive = null; overlay.classList.add("hidden"); overlay.setAttribute("aria-hidden", "true"); button?.setAttribute("aria-expanded", "false"); clearToolSurface({ kind: "command-palette", documentRef }); (trigger ?? documentRef.getElementById("geoStage"))?.focus?.(); }
	function show(source = button) { if (open) { render(); return; } for (const id of ["btnGndImportWorkbenchClose", "btnSpotClose", "btnAlignmentEditorClose", "btnVerticalProfileAuthoringClose", "btnCantAuthoringClose", "btnChainageAuthoringClose"]) documentRef.getElementById(id)?.click?.(); trigger = source; open = true; stopResponsive = watchToolSurface({ surface: overlay, kind: "command-palette", windowRef, documentRef }); overlay.classList.remove("hidden"); overlay.setAttribute("aria-hidden", "false"); button?.setAttribute("aria-expanded", "true"); render(); }
	async function execute(id = selectedId) { if (busy) return false; error = null; const command = model().commands.find((entry) => entry.id === id); if (!command?.enabled) { error = command?.reason ?? "Aktion nicht verfügbar"; render(); return false; } busy = true; render(); try { const result = await availability[command.action].run(); if (result !== true) { error = "Aktion konnte nicht ausgeführt werden"; return false; } close(); return true; } catch (cause) { error = String(cause?.message ?? cause ?? "Aktion fehlgeschlagen"); return false; } finally { busy = false; if (open) render(); } }
	view.setHandlers({ search: (value) => { query = value; selectedId = null; error = null; render(); }, execute });
	const onKey = (event) => { if ((event.ctrlKey || event.metaKey) && String(event.key).toLowerCase() === "k") { event.preventDefault?.(); show(event.target); return; } if (!open) return; if (event.key === "Escape") { event.preventDefault?.(); close(); } else if (event.key === "Enter") { event.preventDefault?.(); void execute(); } };
	const onPeerClick = (event) => { if (open && PEER_OPENERS.has(String(event?.target?.id ?? ""))) close(); };
	button?.addEventListener("click", () => show(button)); documentRef.getElementById("btnCommandPaletteClose")?.addEventListener("click", close); windowRef.addEventListener?.("keydown", onKey); documentRef.addEventListener?.("click", onPeerClick, true);
	return Object.freeze({ open: show, close, execute, getModel: model, stop() { close(); windowRef.removeEventListener?.("keydown", onKey); documentRef.removeEventListener?.("click", onPeerClick, true); } });
}
