import { buildCantAuthoringDockModel } from "../../domain/workspace/buildCantAuthoringDockModel.js";
import { createAuthoringDraftStore,isConfirmedAuthoringSaveResult } from "../../domain/workspace/createAuthoringDraftStore.js";
export function createCantAuthoringDockController({store,profileSource,view,ui}={}){
	if(!store?.getState||!profileSource?.getCurrentProjection||!view?.render) throw new TypeError("Cant authoring dock requires store, profile source and view");
	let request=null,busy=false,unsubscribe=null;const drafts=createAuthoringDraftStore(); const context=()=>({activeObjectId:store.getState()?.workspace_selection?.primaryId??null,projection:profileSource.getCurrentProjection(),...request}); const model=()=>buildCantAuthoringDockModel(context());const identity=(action,current=model())=>({objectId:current.objectId,discipline:"cant",action,elementId:current.elementId}); const render=(status,error=null)=>{const current=model();view.render(current,{status,busy,error,readDraft:action=>drafts.read(identity(action,current))});};
	const capability={submitBasicCant:"canCreateInitial",appendLinearCantElement:"canAppendLinear",updateTerminalConstantCantCrossLevel:"canEditConstant",updateTerminalConstantCantDomain:"canEditConstant",updateTerminalLinearCantComposite:"canEditLinear"};
	async function run(action,payload){const current=model(), exactEdit=!action.startsWith("updateTerminal")||String(payload?.elementId??"").trim()===current.elementId; if(busy||!current[capability[action]]||!exactEdit||typeof profileSource[action]!=="function"){render(current.status==="target-missing"?"target-missing":"unavailable");return false;}drafts.write(identity(action,current),payload); busy=true;render("saving");try{const result=await profileSource[action](payload),saved=isConfirmedAuthoringSaveResult(result);busy=false;if(saved)drafts.clear(identity(action,current));render(saved?"saved":"error",result?.reason??result?.code??null);return saved;}catch(error){busy=false;render("error",String(error?.message??error));return false;}}
	view.setHandlers?.({close:()=>{ui?.closeCantAuthoring?.();request=null;},createInitial:x=>run("submitBasicCant",x),appendLinear:x=>run("appendLinearCantElement",x),editConstantValue:x=>run("updateTerminalConstantCantCrossLevel",x),editConstantDomain:x=>run("updateTerminalConstantCantDomain",x),editLinear:x=>run("updateTerminalLinearCantComposite",x),draftChanged:(action,values)=>drafts.write(identity(action),values)});
	return Object.freeze({open({objectId=null,elementId=null}={}){request={requestedObjectId:objectId,requestedElementId:elementId};ui?.openCantAuthoring?.();render("ready");unsubscribe??=profileSource.subscribeProjection?.(()=>render("ready"));return ["active","selected"].includes(model().status);},close(){ui?.closeCantAuthoring?.();request=null;},stop(){unsubscribe?.();unsubscribe=null;drafts.clearAll();}});
}
export default createCantAuthoringDockController;
