@startuml
left to right direction
skinparam packageStyle rectangle
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide empty members
skinparam package<<legacy>> BackgroundColor #eeeeee


@enduml
