import assert from "node:assert/strict";
import test from "node:test";
import { AlignmentProfileSynchronizedView } from "../../../app/view/alignment-profile/AlignmentProfileSynchronizedView.js";
import { wireAlignmentProfileSynchronizedView } from "../../../app/controllers/alignment-profile/wireAlignmentProfileSynchronizedView.js";

class Element { constructor(ownerDocument, tag="div"){this.ownerDocument=ownerDocument;this.tag=tag;this.children=[];this.dataset={};this.textContent="";this.value="";this.disabled=false;} append(...c){this.children.push(...c);} replaceChildren(...c){this.children=[...c];} setAttribute(){} find(p){for(const c of this.children){if(p(c))return c;const n=c.find?.(p);if(n)return n;}return null;} querySelector(s){const k=s.match(/^\[data-([a-z0-9-]+)\]$/)?.[1]?.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return k?this.find(e=>Object.hasOwn(e.dataset,k)):null;} }
class Document { constructor(){this.panel=new Element(this);} createElement(t){return new Element(this,t);} getElementById(id){return id==="cockpitPanel"?this.panel:null;} }
const projection=(revision=1)=>({status:"projected",alignmentId:"A1",revision,cursor:{parameterKind:"intrinsic-s",s:75},profileStatePresence:"present",vertical:{status:"not-covered"},chainage:{status:"evaluated",candidates:[{segmentId:"CHS2",address:3025}]},cant:{status:"evaluated"}});

test("view submits only explicit mapping segment and direction",()=>{const d=new Document(),host=new Element(d),view=new AlignmentProfileSynchronizedView({host});let submitted;view.setTerminalChainageDirectionEditHandler(v=>{submitted=v;});view.render(projection());const details=host.find(n=>Object.hasOwn(n.dataset,"terminalChainageDirectionEdit"));assert.ok(details);const m=details.find(n=>n.name==="directionEditMappingId"),s=details.find(n=>n.name==="directionEditSegmentId"),dir=details.find(n=>n.name==="directionEditDirection");assert.equal(m.value,"");assert.equal(s.value,"");assert.equal(dir.value,"");m.value="CH1";s.value="CHS2";dir.value="1";details.find(n=>n.tag==="button"&&n.textContent==="Apply terminal direction").onclick();assert.deepEqual(submitted,{mappingId:"CH1",segmentId:"CHS2",direction:"1"});});
test("form is absent for absent chainage",()=>{const d=new Document(),host=new Element(d),view=new AlignmentProfileSynchronizedView({host});view.setTerminalChainageDirectionEditHandler(()=>{});view.render({...projection(),chainage:{status:"absent",mappings:[]}});assert.equal(host.find(n=>Object.hasOwn(n.dataset,"terminalChainageDirectionEdit")),null);});
test("wiring uses canonical context and matching SPOT readback",async()=>{const d=new Document();let revision=1;let profileState={vertical:{alignmentId:"A1"},cant:{alignmentId:"A1"},chainageMappings:[{id:"CH1",alignmentId:"A1",segments:[{id:"CHS1"},{id:"CHS2"}]}]};let received;class View{setTerminalChainageDirectionEditHandler(h){this.handler=h;}renderTerminalChainageDirectionEditStatus(v){this.status=v;}render(v){this.value=v;}}const wiring=wireAlignmentProfileSynchronizedView({store:{getState:()=>({workspace_selection:{primaryId:"A1"},cursor:{s:75}}),subscribe:()=>()=>{}},documentRef:d,messaging:{async sendCmdAwait(){return{objects:[{id:"A1",type:"alignment",data:{alignmentData:{id:"A1",revision,profileState}}}]};}},projectionController:{async projectAt(){return projection(revision);}},terminalChainageSegmentDirectionEditController:{async update(v){received=v;revision=2;profileState={...v.profileState,chainageMappings:[{...v.profileState.chainageMappings[0],edited:true}]};return{snapshot:{revision},profileState,projection:projection(revision)};}},View});const result=await wiring.updateTerminalChainageSegmentDirection({mappingId:"CH1",segmentId:"CHS2",direction:"1"});assert.equal(received.alignmentId,"A1");assert.equal(received.revision,1);assert.equal(received.s,75);assert.equal(result.revision,2);wiring.stop();});
