import assert from "node:assert/strict";
import test from "node:test";
import { AlignmentProfileSynchronizedView } from "../../../app/view/alignment-profile/AlignmentProfileSynchronizedView.js";
import { wireAlignmentProfileSynchronizedView } from "../../../app/controllers/alignment-profile/wireAlignmentProfileSynchronizedView.js";
class E { constructor(d, tag = "div") { this.ownerDocument = d; this.tag = tag; this.children = []; this.dataset = {}; this.textContent = ""; this.value = ""; } append(...children) { this.children.push(...children); } replaceChildren(...children) { this.children = [...children]; } setAttribute() {} find(predicate) { for (const child of this.children) { if (predicate(child)) return child; const found = child.find?.(predicate); if (found) return found; } return null; } querySelector(selector) { const key = selector.match(/^\[data-([a-z0-9-]+)\]$/)?.[1]?.replace(/-([a-z])/g, (_, c) => c.toUpperCase()); return key ? this.find((element) => Object.hasOwn(element.dataset, key)) : null; } }
class D { constructor() { this.panel = new E(this); } createElement(tag) { return new E(this, tag); } getElementById(id) { return id === "cockpitPanel" ? this.panel : null; } }
const c1 = { id: "C1", type: "constant-cross-level", startS: 0, endS: 50, startCrossLevel: 0.04 }, c2 = { id: "C2", type: "linear-cross-level", startS: 50, endS: 125, startCrossLevel: 0.04, crossLevelRate: 0.001 };
const projection = (revision = 1) => ({ status: "projected", alignmentId: "A1", revision, cursor: { parameterKind: "intrinsic-s", s: 75 }, profileStatePresence: "present", vertical: { status: "absent" }, chainage: { status: "absent" }, cant: { status: "evaluated", value: { elementId: "C2", crossLevel: 0.065, twist: 0.001 } } });
test("view exposes exact terminal identity and submits only rate and endS", () => { const d = new D(), host = new E(d), view = new AlignmentProfileSynchronizedView({ host }); let sent; view.setTerminalLinearCantCompositeHandler((value) => { sent = value; }); view.render({ ...projection(), terminalCantElement: c2 }); const details = host.find((node) => Object.hasOwn(node.dataset, "terminalLinearCantCompositeEdit")); assert.ok(details); assert.deepEqual(JSON.parse(details.find((node) => Object.hasOwn(node.dataset, "terminalLinearCantCompositeIdentity")).textContent), { elementId: "C2", type: "linear-cross-level", startS: 50, endS: 125, startCrossLevel: 0.04, crossLevelRate: 0.001 }); const rate = details.find((node) => node.name === "terminalLinearCantCompositeRate"), end = details.find((node) => node.name === "terminalLinearCantCompositeEndS"); assert.equal(rate.value, "0.001"); assert.equal(end.value, "125"); rate.value = "0.002"; end.value = "150"; details.find((node) => node.tag === "button" && node.textContent === "Apply linear Cant fields").onclick(); assert.deepEqual(sent, { elementId: "C2", crossLevelRate: "0.002", endS: "150" }); view.render({ ...projection(), terminalCantElement: c1 }); assert.equal(host.find((node) => Object.hasOwn(node.dataset, "terminalLinearCantCompositeEdit")), null); });
test("wiring uses exact canonical context and matching SPOT readback", async () => { const d = new D(); let revision = 1, received, renderedStatus; let profileState = { vertical: null, cant: { id: "CANT1", alignmentId: "A1", elements: [c1, c2] }, chainageMappings: [] }; class View { setTerminalLinearCantCompositeHandler(handler) { this.handler = handler; } renderTerminalLinearCantCompositeStatus(value) { renderedStatus = value; } render(value) { this.value = value; } } const wiring = wireAlignmentProfileSynchronizedView({ store: { getState: () => ({ workspace_selection: { primaryId: "A1" }, cursor: { s: 75 } }), subscribe: () => () => {} }, documentRef: d, messaging: { async sendCmdAwait() { return { objects: [{ id: "A1", type: "alignment", data: { alignmentData: { id: "A1", revision, profileState } } }] }; } }, projectionController: { async projectAt() { return projection(revision); } }, terminalLinearCantCompositeEditController: { async update(value) { received = value; revision = 2; profileState = { ...value.profileState, cant: { ...value.profileState.cant, elements: [c1, { ...c2, crossLevelRate: 0.002, endS: 150 }] } }; return { snapshot: { revision }, profileState, projection: projection(revision) }; } }, View }); const result = await wiring.updateTerminalLinearCantComposite({ elementId: "C2", crossLevelRate: "0.002", endS: "150" }); assert.equal(received.alignmentId, "A1"); assert.equal(received.revision, 1); assert.equal(received.s, 75); assert.equal(result.snapshot.revision, 2); assert.equal(renderedStatus, "saved"); wiring.stop(); });
