import assert from "node:assert/strict";
import test from "node:test";
import { appendChainageSegment, createChainageMapping, mapChainageToIntrinsic, mapIntrinsicToChainage } from "../../../src/aim-core/alignment/profile/ChainageMapping.js";
import { createTerminalChainageSegmentRemoveController } from "../../../app/controllers/alignment-profile/createTerminalChainageSegmentRemoveController.js";

let mapping=appendChainageSegment(createChainageMapping({id:"CH1",alignmentId:"A1",schemeId:"scheme-demo",schemeVersion:"v1"}),{id:"CHS1",startS:0,endS:50,startAddress:1000,direction:1,prefixExtension:"kept"});
mapping=appendChainageSegment(mapping,{id:"CHS2",startS:50,endS:100,startAddress:3000,direction:1,terminalExtension:true});
mapping=Object.freeze({...mapping,mappingExtension:{source:"persisted"}});
const vertical={alignmentId:"A1",id:"V1"},cant={alignmentId:"A1",id:"CANT1",elements:[{id:"C2"}]},other={alignmentId:"A1",id:"OTHER"},profileExtension={kept:true};
const profileState={vertical,cant,chainageMappings:[mapping,other],profileExtension};
const projection=(revision,s)=>({alignmentId:"A1",revision,cursor:{parameterKind:"intrinsic-s",s},chainage:{status:s>50?"not-covered":"evaluated"}});
function harness({stale=false,mismatch=false,failure=null}={}){let writes=0;const controller=createTerminalChainageSegmentRemoveController({alignmentProfileApplicationService:{async saveProfileState({profileState:next}){writes++;if(failure)throw failure;return{presence:"present",revision:2,vertical:next.vertical,cant:next.cant,chainageMappings:mismatch?profileState.chainageMappings:next.chainageMappings};}},projectionController:{async projectAt({revision,s}){return projection(stale?99:revision,s);}}});return{controller,writes:()=>writes};}
const request={alignmentId:"A1",revision:1,s:75,profileState,mappingId:"CH1",segmentId:"CHS2"};
test("removes only terminal CHS2 and canonically retains CHS1",async()=>{const h=harness(),result=await h.controller.remove(request);assert.equal(h.writes(),1);assert.strictEqual(result.profileState.vertical,vertical);assert.strictEqual(result.profileState.cant,cant);assert.strictEqual(result.profileState.chainageMappings[1],other);assert.strictEqual(result.profileState.profileExtension,profileExtension);assert.strictEqual(result.mapping.mappingExtension,mapping.mappingExtension);assert.deepEqual(result.mapping.segments,[mapping.segments[0]]);assert.deepEqual(result.forwardCandidates,[]);assert.deepEqual(mapIntrinsicToChainage(result.mapping,{s:25}),[{segmentId:"CHS1",s:25,address:1025,schemeId:"scheme-demo",schemeVersion:"v1",unit:"alignment-length-unit"}]);assert.deepEqual(mapIntrinsicToChainage(result.mapping,{s:50}),[{segmentId:"CHS1",s:50,address:1050,schemeId:"scheme-demo",schemeVersion:"v1",unit:"alignment-length-unit"}]);assert.deepEqual(mapChainageToIntrinsic(result.mapping,{address:1025}),[{segmentId:"CHS1",address:1025,s:25,alignmentId:"A1",schemeId:"scheme-demo",schemeVersion:"v1",unit:"alignment-length-unit"}]);});
test("invalid wrong nonterminal duplicate stale and sole targets are zero-write",async()=>{for(const changes of[{mappingId:""},{segmentId:""},{segmentId:"CHS1"},{mappingId:"missing"}]){const h=harness();await assert.rejects(h.controller.remove({...request,...changes}));assert.equal(h.writes(),0);}const dup=harness();await assert.rejects(dup.controller.remove({...request,profileState:{...profileState,chainageMappings:[mapping,mapping]}}),{code:"CHAINAGE_MAPPING_IDENTITY_MISMATCH"});assert.equal(dup.writes(),0);const dupMap=Object.freeze({...mapping,segments:[...mapping.segments,mapping.segments[1]]});const ds=harness();await assert.rejects(ds.controller.remove({...request,profileState:{...profileState,chainageMappings:[dupMap]}}),{code:"CHAINAGE_SEGMENT_IDENTITY_MISMATCH"});assert.equal(ds.writes(),0);const single={...mapping,segments:[mapping.segments[1]]};const sole=harness();await assert.rejects(sole.controller.remove({...request,profileState:{...profileState,chainageMappings:[single]}}),{code:"CHAINAGE_SEGMENT_REMOVE_WOULD_EMPTY_MAPPING"});assert.equal(sole.writes(),0);const stale=harness({stale:true});await assert.rejects(stale.controller.remove(request),{code:"PROFILE_READBACK_MISMATCH"});assert.equal(stale.writes(),0);});
test("save and readback failures never report removal",async()=>{const mismatch=harness({mismatch:true});await assert.rejects(mismatch.controller.remove(request),{code:"PROFILE_READBACK_MISMATCH"});assert.equal(mismatch.writes(),1);const failure=harness({failure:new Error("offline")});await assert.rejects(failure.controller.remove(request),{code:"TERMINAL_CHAINAGE_REMOVE_SAVE_FAILED"});assert.equal(failure.writes(),1);});
