import assert from "node:assert/strict";
import { registerHooks } from "node:module";
import test from "node:test";
const rootUrl=new URL("../../../",import.meta.url),aliases={"@app/":"app/","@src/":"src/","@utils/":"src/lib/utils/","@spot/":"src/model/spot/","@transition/":"src/domain/transition/"};registerHooks({resolve(specifier,context,nextResolve){for(const[prefix,target]of Object.entries(aliases))if(specifier.startsWith(prefix))return nextResolve(new URL(target+specifier.slice(prefix.length),rootUrl).href,context);return nextResolve(specifier,context);}});
const {buildHorizontalSequenceAddRequest}=await import("../../../app/controllers/alignmentCreationController.js");

test("straight requires an explicit positive length",()=>{assert.deepEqual(buildHorizontalSequenceAddRequest({type:"straight",length:"125.5"}),{ok:true,method:"straight",args:{length:125.5}});for(const length of ["",0,-1,"x"])assert.equal(buildHorizontalSequenceAddRequest({type:"straight",length}).ok,false);});
test("arc carries exactly the selected signed authority without reciprocal derivation",()=>{assert.deepEqual(buildHorizontalSequenceAddRequest({type:"arc",length:"80",arcAuthority:"curvature",signedValue:"-0.002"}),{ok:true,method:"arc",args:{length:80,curvature:-0.002}});assert.deepEqual(buildHorizontalSequenceAddRequest({type:"arc",length:80,arcAuthority:"radius",signedValue:"-500"}),{ok:true,method:"arc",args:{length:80,radius:-500}});assert.equal(buildHorizontalSequenceAddRequest({type:"arc",length:80,signedValue:0.002}).ok,false);assert.equal(buildHorizontalSequenceAddRequest({type:"arc",length:80,arcAuthority:"radius",signedValue:""}).ok,false);});
test("transition accepts only an exact live-catalogue family and paired optional cuts",()=>{const availableTransitionTypes=["clothoid","bloss"];assert.deepEqual(buildHorizontalSequenceAddRequest({type:"transition",length:60,transitionType:"bloss",w1:"0.2",w2:"0.3",availableTransitionTypes}),{ok:true,method:"transition",args:{length:60,transitionType:"bloss",w1:0.2,w2:0.3}});assert.deepEqual(buildHorizontalSequenceAddRequest({type:"transition",length:60,transitionType:"bloss",availableTransitionTypes}),{ok:true,method:"transition",args:{length:60,transitionType:"bloss"}});assert.equal(buildHorizontalSequenceAddRequest({type:"transition",length:60,transitionType:"bloss",w1:"0.2",availableTransitionTypes}).code,"TRANSITION_PARAMETER_PAIR_REQUIRED");assert.equal(buildHorizontalSequenceAddRequest({type:"transition",length:60,transitionType:"bloss",w2:"0.3",availableTransitionTypes}).code,"TRANSITION_PARAMETER_PAIR_REQUIRED");assert.equal(buildHorizontalSequenceAddRequest({type:"transition",length:60,transitionType:"invented",availableTransitionTypes}).ok,false);});
