import assert from "node:assert/strict";
import test from "node:test";
import { buildHorizontalSequenceConsequenceReview } from "../../../app/domain/workspace/buildHorizontalSequenceConsequenceReview.js";

test("review binds exact ordered edit IDs to existing sparse consequences only",()=>{const alignmentData={id:"A",editModel:{elements:[{id:"S1",type:"straight",parameters:{length:50},meta:{createdBy:"editor"}},{id:"T1",type:"transition",parameters:{length:30,transitionType:"bloss"}},{id:"A1",type:"arc",parameters:{length:80,curvature:-.002}}]},sparseAlignment:{elements:[{id:"S1",type:"fixed",kind:"straight",arcLength:50,curvature:0,sStart:0,sEnd:50,meta:{derivedBy:"existing"}},{id:"T1",type:"transition",arcLength:30,sStart:50,sEnd:80},{id:"A1",type:"fixed",kind:"arc",arcLength:80,curvature:-.002,sStart:80,sEnd:160}]}};const model=buildHorizontalSequenceConsequenceReview({alignmentData,spotObject:{id:"A"}});assert.deepEqual(model.rows.map(x=>x.id),["S1","T1","A1"]);assert.deepEqual(model.rows[0].domain,{startS:0,endS:50});assert.equal(model.rows[0].startCurvature,0);assert.equal(model.rows[1].curvatureStatus,"not-covered");assert.equal(model.rows[1].continuity.status,"not-covered");assert.equal(model.rows[2].startCurvature,-.002);assert.equal(model.rows[2].endCurvature,-.002);});
test("only existing validation continuity and provenance are transported",()=>{const model=buildHorizontalSequenceConsequenceReview({alignmentData:{id:"A",editModel:{elements:[{id:"T",type:"transition",parameters:{length:20},validation:{status:"review-required",code:"EXISTING",sourceRefs:["x"]},continuity:{status:"passed",provenance:{id:"p"}}}]}}});assert.deepEqual(model.rows[0].validation,{status:"review-required",code:"EXISTING",provenancePresent:true});assert.deepEqual(model.rows[0].continuity,{status:"passed",code:null,provenancePresent:true});assert.equal(model.validation.status,"not-covered");});
test("missing length remains uncovered instead of becoming numeric zero",()=>{const model=buildHorizontalSequenceConsequenceReview({alignmentData:{id:"A",editModel:{elements:[{id:"X",type:"transition",parameters:{}}]}}});assert.equal(model.rows[0].length,null);});
test("transition never borrows fixed sparse curvature solely from a matching id",()=>{const model=buildHorizontalSequenceConsequenceReview({alignmentData:{id:"A",editModel:{elements:[{id:"T",type:"transition",parameters:{length:20}}]},sparseAlignment:{elements:[{id:"T",type:"fixed",kind:"arc",curvature:.004,sStart:0,sEnd:20}]}}});assert.equal(model.rows[0].curvatureStatus,"not-covered");assert.equal(model.rows[0].startCurvature,null);});
test("empty or unprovenanced findings remain not-covered",()=>{const model=buildHorizontalSequenceConsequenceReview({alignmentData:{id:"A",validation:{},continuity:{status:"passed"},editModel:{elements:[{id:"S",type:"straight",parameters:{length:10},validation:{ok:true},continuity:{code:"C0"}}]}}});assert.equal(model.validation.status,"not-covered");assert.equal(model.continuity.status,"not-covered");assert.equal(model.rows[0].validation.status,"not-covered");assert.equal(model.rows[0].continuity.status,"not-covered");});
